/*
   quarta-feira, 10 de maio de 2006 16:28:52
   User: sa
   Server: ONLYTECH-DADOS
   Database: BDPDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
CREATE TABLE dbo.Tmp_TBParametros_fiscais
	(
	PKId_TBParametros_fiscais int NOT NULL,
	PKCodigo_TBEmpresa int NOT NULL,
	DFProximo_cfop_venda_dentro_estado_TBParametros_fiscais int NOT NULL,
	DFProximo_cfop_venda_fora_estado_TBParametros_fiscais int NOT NULL,
	DFProximo_cfop_venda_dentro_substituicao_estado_TBParametros_fiscais int NOT NULL,
	DFProximo_cfop_venda_fora_estado_substituicao_TBParametros_fiscais int NOT NULL,
	DFProximo_cfop_transferencia_dentro_estado_TBParametros_fiscais int NOT NULL,
	DFProximo_cfop_transferencia_fora_estado_TBParametros_fiscais int NOT NULL,
	DFProximo_cfop_devolucao_cliente_dentro_estado_TBParametros_fiscais int NOT NULL,
	DFProximo_cfop_devolucao_cliente_fora_estado_TBParametros_fiscais int NOT NULL,
	DFProximo_cfop_devolucao_fornecedor_dentro_estado_TBParametros_fiscais int NOT NULL,
	DFProximo_cfop_devolucao_fornecedor_fora_estado_TBParametros_fiscais int NOT NULL,
	DFProximo_livro_entrada_TBParametros_fiscais int NOT NULL,
	DFNumero_paginas_livro_entrada_TBParametros_fiscais int NOT NULL,
	DFProximo_pagina_livro_entrada_TBParametros_fiscais int NULL,
	DFProximo_livro_saida_TBParametros_fiscais int NULL,
	DFProximo_pagina_livro_saida_TBParametros_fiscais int NULL,
	DFNumero_paginas_livro_saida_TBParametros_fiscais int NULL,
	DFPercentual_pis_TBParametros_fiscais money NULL,
	DFPercentual_cofins_TBParametros_fiscais money NULL,
	DFProxima_carta_correcao_TBParametros_fiscais int NULL
	)  ON [PRIMARY]
GO
IF EXISTS(SELECT * FROM dbo.TBParametros_fiscais)
	 EXEC('INSERT INTO dbo.Tmp_TBParametros_fiscais (PKId_TBParametros_fiscais, PKCodigo_TBEmpresa, DFProximo_cfop_venda_dentro_estado_TBParametros_fiscais, DFProximo_cfop_venda_fora_estado_TBParametros_fiscais, DFProximo_cfop_venda_dentro_substituicao_estado_TBParametros_fiscais, DFProximo_cfop_venda_fora_estado_substituicao_TBParametros_fiscais, DFProximo_cfop_transferencia_dentro_estado_TBParametros_fiscais, DFProximo_cfop_transferencia_fora_estado_TBParametros_fiscais, DFProximo_cfop_devolucao_cliente_dentro_estado_TBParametros_fiscais, DFProximo_cfop_devolucao_cliente_fora_estado_TBParametros_fiscais, DFProximo_cfop_devolucao_fornecedor_dentro_estado_TBParametros_fiscais, DFProximo_cfop_devolucao_fornecedor_fora_estado_TBParametros_fiscais, DFProximo_livro_entrada_TBParametros_fiscais, DFNumero_paginas_livro_entrada_TBParametros_fiscais, DFProximo_pagina_livro_entrada_TBParametros_fiscais, DFProximo_livro_saida_TBParametros_fiscais, DFProximo_pagina_livro_saida_TBParametros_fiscais, DFNumero_paginas_livro_saida_TBParametros_fiscais, DFPercentual_pis_TBParametros_fiscais, DFPercentual_cofins_TBParametros_fiscais, DFProxima_carta_correcao_TBParametros_fiscais)
		SELECT PKId_TBParametros_fiscais, PKCodigo_TBEmpresa, DFProximo_cfop_venda_dentro_estado_TBParametros_fiscais, DFProximo_cfop_venda_fora_estado_TBParametros_fiscais, DFProximo_cfop_venda_dentro_substituicao_estado_TBParametros_fiscais, DFProximo_cfop_venda_fora_estado_substituicao_TBParametros_fiscais, DFProximo_cfop_transferencia_dentro_estado_TBParametros_fiscais, DFProximo_cfop_transferencia_fora_estado_TBParametros_fiscais, DFProximo_cfop_devolucao_cliente_dentro_estado_TBParametros_fiscais, DFProximo_cfop_devolucao_cliente_fora_estado_TBParametros_fiscais, DFProximo_cfop_devolucao_fornecedor_dentro_estado_TBParametros_fiscais, DFProximo_cfop_devolucao_fornecedor_fora_estado_TBParametros_fiscais, DFProximo_livro_entrada_TBParametros_fiscais, DFNumero_paginas_livro_entrada_TBParametros_fiscais, DFProximo_pagina_livro_entrada_TBParametros_fiscais, DFProximo_livro_saida_TBParametros_fiscais, DFProximo_pagina_livro_saida_TBParametros_fiscais, DFNumero_paginas_livro_saida_TBParametros_fiscais, DFPercentual_pis_TBParametros_fiscais, DFPercentual_cofins_TBParametros_fiscais, DFProxima_carta_correcao_TBParametros_fiscais FROM dbo.TBParametros_fiscais TABLOCKX')
GO
DROP TABLE dbo.TBParametros_fiscais
GO
EXECUTE sp_rename N'dbo.Tmp_TBParametros_fiscais', N'TBParametros_fiscais', 'OBJECT'
GO
ALTER TABLE dbo.TBParametros_fiscais ADD CONSTRAINT
	PK_TBParametros_fiscais PRIMARY KEY CLUSTERED 
	(
	PKId_TBParametros_fiscais
	) ON [PRIMARY]

GO
COMMIT
