/*
   sexta-feira, 5 de maio de 2006 19:39:18
   User: sa
   Server: ONLYTECH-DADOS
   Database: BDPDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBCodigo_barras
	DROP CONSTRAINT FK__TBCodigo___FKId___3D7E1B63
GO
COMMIT
BEGIN TRANSACTION
COMMIT
