/*
   sexta-feira, 5 de maio de 2006 19:40:24
   User: sa
   Server: ONLYTECH-DADOS
   Database: BDPDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBProduto
	DROP CONSTRAINT FK__TBProduto__IXCod__36D11DD4
GO
ALTER TABLE dbo.TBVendedor
	DROP CONSTRAINT FK__TBVendedo__IXCod__37C5420D
GO
ALTER TABLE dbo.TBParametros_ecf
	DROP CONSTRAINT FK__TBParamet__FKCod__3AA1AEB8
GO
ALTER TABLE dbo.TBOperadores_ecf
	DROP CONSTRAINT FK__TBOperado__FKCod__3B95D2F1
GO
ALTER TABLE dbo.TBParametros_fiscais
	DROP CONSTRAINT FK__TBParamet__PKCod__3C89F72A
GO
ALTER TABLE dbo.TBOperacao_caixa
	DROP CONSTRAINT FK_TBOperacao_caixa_TBEmpresa
GO
ALTER TABLE dbo.TBPdv
	DROP CONSTRAINT FK_TBPdv_TBEmpresa
GO
ALTER TABLE dbo.TBDia_operacao_pdv
	DROP CONSTRAINT FK_TBDia_operacao_pdv_TBEmpresa
GO
ALTER TABLE dbo.TBTanque
	DROP CONSTRAINT FK__TBTanque__IXCodi__63A3C44B
GO
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
