/*
   sexta-feira, 5 de maio de 2006 19:44:37
   User: sa
   Server: ONLYTECH-DADOS
   Database: BDPDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBOcorrencia_produto
	DROP CONSTRAINT FK__TBOcorren__FKId___405A880E
GO
ALTER TABLE dbo.TBBomba_bico
	DROP CONSTRAINT FK__TBBomba_b__FKId___6497E884
GO
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
