/*
   sexta-feira, 5 de maio de 2006 19:43:10
   User: sa
   Server: ONLYTECH-DADOS
   Database: BDPDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBOperacao_caixa
	DROP CONSTRAINT FK__TBOperaca__FKCof__48EFCE0F
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBOperacao_caixa
	DROP CONSTRAINT FK__TBOperaca__FKCod__47FBA9D6
GO
COMMIT
BEGIN TRANSACTION
COMMIT
