/*
   sexta-feira, 5 de maio de 2006 19:39:55
   User: sa
   Server: ONLYTECH-DADOS
   Database: BDPDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBCupom
	DROP CONSTRAINT FK_TBCupom_TBOperadores_ecf
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBCupom
	DROP CONSTRAINT FK__TBCupom__PKCodig__49E3F248
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBCupom
	DROP CONSTRAINT FK__TBCupom__FKId_TB__4336F4B9
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBCupom
	DROP CONSTRAINT FK__TBCupom__FKCodig__39AD8A7F
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBItens_cupom
	DROP CONSTRAINT FK__TBItens_c__FKId___4707859D
GO
ALTER TABLE dbo.TBImpostos_cupom
	DROP CONSTRAINT FK__TBImposto__FKId___46136164
GO
COMMIT
BEGIN TRANSACTION
COMMIT
BEGIN TRANSACTION
COMMIT
