/*
   sexta-feira, 28 de abril de 2006 15:32:06
   User: sa
   Server: ONLYTECH-02
   Database: BDPDV
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBVendedor
	DROP CONSTRAINT FK__TBVendedo__IXCod__37C5420D
GO
COMMIT
BEGIN TRANSACTION
CREATE TABLE dbo.Tmp_TBVendedor
	(
	PKId_TBVendedor int NOT NULL,
	IXCodigo_TBEmpresa int NOT NULL,
	IXCodigo_TBVendedor int NOT NULL,
	DFNome_TBVendedor nvarchar(40) NOT NULL
	)  ON [PRIMARY]
GO
IF EXISTS(SELECT * FROM dbo.TBVendedor)
	 EXEC('INSERT INTO dbo.Tmp_TBVendedor (PKId_TBVendedor, IXCodigo_TBEmpresa, IXCodigo_TBVendedor, DFNome_TBVendedor)
		SELECT PKId_TBVendedor, IXCodigo_TBEmpresa, IXCodigo_TBVendedor, DFNome_TBVendedor FROM dbo.TBVendedor TABLOCKX')
GO
ALTER TABLE dbo.TBCupom
	DROP CONSTRAINT FK__TBCupom__FKId_TB__4336F4B9
GO
DROP TABLE dbo.TBVendedor
GO
EXECUTE sp_rename N'dbo.Tmp_TBVendedor', N'TBVendedor', 'OBJECT'
GO
ALTER TABLE dbo.TBVendedor ADD CONSTRAINT
	PK__TBVendedor__15702A09 PRIMARY KEY CLUSTERED 
	(
	PKId_TBVendedor
	) ON [PRIMARY]

GO
ALTER TABLE dbo.TBVendedor WITH NOCHECK ADD CONSTRAINT
	FK__TBVendedo__IXCod__37C5420D FOREIGN KEY
	(
	IXCodigo_TBEmpresa
	) REFERENCES dbo.TBEmpresa
	(
	PKCodigo_TBEmpresa
	)
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBCupom WITH NOCHECK ADD CONSTRAINT
	FK__TBCupom__FKId_TB__4336F4B9 FOREIGN KEY
	(
	FKId_TBVendedor
	) REFERENCES dbo.TBVendedor
	(
	PKId_TBVendedor
	)
GO
COMMIT
