
DELETE FROM TBESTADO_ICMS
WHERE FKId_TBProduto IN (SELECT PKID_TBPRODUTO FROM TBPRODUTO WHERE TBPRODUTO.IXCodigo_TBEmpresa <> 500)

DELETE FROM TBITENS_TABELA_PRECO
WHERE FKId_TBProduto IN (SELECT PKID_TBPRODUTO FROM TBPRODUTO WHERE TBPRODUTO.IXCodigo_TBEmpresa <> 500)

DELETE FROM TBProduto_receita
WHERE FKId_TBProduto IN (SELECT PKID_TBPRODUTO FROM TBPRODUTO WHERE TBPRODUTO.IXCodigo_TBEmpresa <> 500)

DELETE FROM TBITENS_NOTA_ENTRADA_FISCAL
WHERE FKId_TBProduto IN (SELECT PKID_TBPRODUTO FROM TBPRODUTO WHERE TBPRODUTO.IXCodigo_TBEmpresa <> 500)

DELETE FROM TBGRADE_NOTA_ENTRADA
WHERE FKCodigo_TBEmpresa  <> 500

DELETE FROM TBESTOQUE_GRADE
WHERE FKCodigo_TBEmpresa  <> 500

DELETE FROM TBITENS_NOTA_ENTRADA
WHERE FKId_TBProduto IN (SELECT PKID_TBPRODUTO FROM TBPRODUTO WHERE TBPRODUTO.IXCodigo_TBEmpresa <> 500)

DELETE FROM TBItens_ordem_compra
WHERE FKId_TBProduto IN (SELECT PKID_TBPRODUTO FROM TBPRODUTO WHERE TBPRODUTO.IXCodigo_TBEmpresa <> 500)

DELETE FROM TBPRODUTO
WHERE TBPRODUTO.IXCodigo_TBEmpresa <> 500
