/*
   sexta-feira, 4 de novembro de 2005 17:55:57
   User: 
   Server: ONLYTECH-02
   Database: BDRetaguarda
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
CREATE NONCLUSTERED INDEX IX_TBTitulo_receber ON dbo.TBTitulo_receber
	(
	FKCodigo_TBEmpresa
	) ON [PRIMARY]
GO
COMMIT
