/*
   quarta-feira, 8 de março de 2006 15:02:45
   User: sa
   Server: ONLYTECH-02
   Database: BDPortal
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TBTriagem_portal
	DROP CONSTRAINT FK__TBTriagem__FKCod__0DAF0CB0
GO
COMMIT
BEGIN TRANSACTION
COMMIT
